[package]
name = "tab-service-test"
version = "0.1.0"
authors = ["Austin Jones <austin.jones@threatx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
tokio = { version = "0.2" }