use serde::{Deserialize, Serialize};

/// Serializes an indexed chunk of stdout
/// Send by a single running PTY process.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct OutputChunk {
    /// The message index, generated by the PTY process.
    pub index: usize,
    /// Raw bytes of stdout
    pub data: Vec<u8>,
}

impl OutputChunk {
    /// The data buffer length
    pub fn len(&self) -> usize {
        self.data.len()
    }
}

/// Serialize an unindexed chunk of stdin.
/// May be sent by multiple CLI connections.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct InputChunk {
    /// Raw bytes of stdin
    pub data: Vec<u8>,
}

impl InputChunk {
    /// THe data buffer length
    pub fn len(&self) -> usize {
        self.data.len()
    }
}
